### ISSUE TITLE
Mystic "Error!: Invalide DICe executable: dice"

### ISSUE THREAD

**Issue by manpan-1** [dicengine/dicegui#15]
On dicequi startup, I get a error messagebox:

"Error!: Invalide DICe executable: dice"

Pressing Ok, the program just goes on. The error is produced by the `testForDebugMsg()` function on line 139 of utils.js. I don't know if it has further implications other than not having debug messages.

Opensuse Leap 15.1
node v10.16.3
npm 6.12.0
electron v6.0.12

**Comment by dicengine** [comment]
This mystic error means that something got messed up as DICe initialized. It was likely caused by the GUI reading an invalid working directory from the .dice.js file in your home directory. I am going to push a commit in day or two that will fix this. In the mean time, you can delete your .dice.js file. This is likely also the cause of the null folder issue #16

**Comment by manpan-1** [comment]
Yes, the messagebox stopped appearing after I manually set the working dir, as it was using the same on the next startup. Indeed, removing dice.js defaults to home for working dir so it also works. All these issues originate from having null working dir. Thanks!
